### ISSUE TITLE
Wrong colour shown

### ISSUE THREAD

**Issue by chungfk** [yannickl/YLProgressBar#45]
Hi, I've specified a particular colour for my progress bar but what is shown is different from what I specified.

Here is the screenshot:

![screen shot 2016-08-12 at 4 31 29 pm](https://cloud.githubusercontent.com/assets/2288909/17617033/467aee08-60aa-11e6-807a-8cdd0c5750b3.png)

As seen in screenshot, the colour I wanted is selected under the properties which is light green (#8CE600) but wrong colour is shown in the xib file.

**Comment by chungfk** [comment]
i've tried setting it to 1.0 for the progress and the colour that i wanted is shown towards the end. I want the whole bar to be of one colour only.

**Comment by yannickl** [comment]
Hi,

Sorry for the late (I'm in holidays), but yes this is the normal behaviour. There is a gradiant that is auto applied to the color. For the moment to avoid it you'll need to use the `progressTintColors` instead of `progressTintColor` and set the same left and right color.

However now (after 4 years of existence) I think this is a wrong behaviour. To fix it without breaking the API I'm going to add a new property to have an uniform color.

**Comment by yannickl** [comment]
I added a `uniformTintColor` property. Just set it to `YES` and it should work as expected! :)
